# Generated by Django 3.2.10 on 2023-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dep_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
